buildkite:
  # Buildkite API token
  token: <%= ENV['BUILDKITE_TOKEN'] %>
  # the organization to poll
  organization: <%= ENV['BUILDKITE_ORGANIZATION'] %>

bitbucket:
  # username and password with permission to write to the builds
  username: <%= ENV['BITBUCKET_USERNAME'] %>
  password: <%= ENV['BITBUCKET_PASSWORD'] %>
  # URL of bitbucket server
  url: <%= ENV['BITBUCKET_URL'] %>

# Dead Man's Snitch - reports success to the snitch ID on a successful update
dms:
  snitch_id: <%= ENV['DMS_SNITCH_ID'] %>

monitor:
  log_level: <%= ENV['MONITOR_LOG_LEVEL'] || 'WARN' %>
  # number of seconds between polls
  polling_interval: <%= ENV['MONITOR_POLLING_INTERVAL'] || 60 %>
  # how far back in time to look for old builds when first starting the monitor,
  # in hours
  initial_search_time: <%= ENV['MONITOR_INITIAL_SEARCH_TIME'] || 168 %>

